import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import NavMob from "./components/NavMob";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=' flex relative flex-col sm:flex-row justify-between items-center gap-6 sm:p-6  h-screen bg-[#000]'>
        <Navbar />
        <NavMob />
        <div className=' mt-16 sm:mt-0 w-full bg-[#121212] h-full rounded-3xl p-4 overflow-x-hidden shadow-[inset_0px_0px_50px_0px_#17020242] '>
          
        {children}
        </div>
    </div>
      </body>
    </html>
  );
}
